markdown: kramdown
include: [_data]

title: Alan Lai
owner: Alan Lai
email: alan.lai@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  

  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://anlai.github.io" # the base hostname & protocol for your site, e.g. http://example.com

social:
  - type: github
    url: https://github.com/anlai
  - type: linkedin
    url: https://www.linkedin.com/in/alan-n-lai/

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title_suffix: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true